import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const OBJECTS_FILE = path.resolve(__dirname, "../data/words/objects.json");

const newObjectsList: { word: string; category: string; contextClue: string }[] = [
  // Originales
  { word: "Martillo", category: "Objetos", contextClue: "Construcción" },
  { word: "Destornillador", category: "Objetos", contextClue: "Tornillos" },
  { word: "Tijera", category: "Objetos", contextClue: "Costura" },
  { word: "Linterna", category: "Objetos", contextClue: "Oscuridad" },
  { word: "Paraguas", category: "Objetos", contextClue: "Lluvia" },
  { word: "Cámara de fotos", category: "Objetos", contextClue: "Lentes" },
  { word: "Reloj pulsera", category: "Objetos", contextClue: "Agujas" },
  { word: "Auriculares", category: "Objetos", contextClue: "Audio" },
  { word: "Mochila", category: "Objetos", contextClue: "Viaje" },
  { word: "Llave", category: "Objetos", contextClue: "Cerradura" },
  { word: "Candado", category: "Objetos", contextClue: "Seguridad" },
  { word: "Billetera", category: "Objetos", contextClue: "Bolsillo" },
  { word: "Lentes de sol", category: "Objetos", contextClue: "Verano" },
  { word: "Termo", category: "Objetos", contextClue: "Mate" },
  { word: "Cafetera", category: "Objetos", contextClue: "Desayuno" },
  { word: "Tostadora", category: "Objetos", contextClue: "Pan" },
  { word: "Microondas", category: "Objetos", contextClue: "Calentar" },
  { word: "Heladera", category: "Objetos", contextClue: "Frío" },
  { word: "Lavarropas", category: "Objetos", contextClue: "Espuma" },
  { word: "Plancha", category: "Objetos", contextClue: "Vapor" },
  { word: "Aspiradora", category: "Objetos", contextClue: "Polvo" },
  { word: "Televisor", category: "Objetos", contextClue: "Control remoto" },
  { word: "Guitarra", category: "Objetos", contextClue: "Cuerdas" },
  { word: "Piano", category: "Objetos", contextClue: "Teclas" },
  { word: "Batería", category: "Objetos", contextClue: "Platillos" },
  { word: "Micrófono", category: "Objetos", contextClue: "Voz" },
  { word: "Espejo", category: "Objetos", contextClue: "Reflejo" },
  { word: "Cepillo de dientes", category: "Objetos", contextClue: "Baño" },
  { word: "Peine", category: "Objetos", contextClue: "Pelo" },
  { word: "Toalla", category: "Objetos", contextClue: "Secado" },
  { word: "Jabón", category: "Objetos", contextClue: "Burbujas" },
  { word: "Perfume", category: "Objetos", contextClue: "Aroma" },
  { word: "Almohada", category: "Objetos", contextClue: "Dormir" },
  { word: "Sábana", category: "Objetos", contextClue: "Cama" },
  { word: "Lámpara", category: "Objetos", contextClue: "Foco" },
  { word: "Vela", category: "Objetos", contextClue: "Cera" },
  { word: "Encendedor", category: "Objetos", contextClue: "Chispa" },
  { word: "Fósforos", category: "Objetos", contextClue: "Madera" },
  { word: "Cuchillo", category: "Objetos", contextClue: "Filo" },
  { word: "Tenedor", category: "Objetos", contextClue: "Comedor" },
  { word: "Cuchara", category: "Objetos", contextClue: "Sopa" },
  { word: "Plato", category: "Objetos", contextClue: "Cerámica" },
  { word: "Vaso", category: "Objetos", contextClue: "Vidrio" },
  { word: "Copa", category: "Objetos", contextClue: "Brindis" },
  { word: "Sartén", category: "Objetos", contextClue: "Fuego" },
  { word: "Olla", category: "Objetos", contextClue: "Cocción" },
  { word: "Rallador", category: "Objetos", contextClue: "Queso" },
  { word: "Colador", category: "Objetos", contextClue: "Fideos" },
  { word: "Sacacorchos", category: "Objetos", contextClue: "Vino" },
  { word: "Abridor", category: "Objetos", contextClue: "Chapa" },
  { word: "Valija", category: "Objetos", contextClue: "Aeropuerto" },
  { word: "Pasaporte", category: "Objetos", contextClue: "Frontera" },
  { word: "Mapa", category: "Objetos", contextClue: "Rumbo" },
  { word: "Brújula", category: "Objetos", contextClue: "Norte" },
  { word: "Telescopio", category: "Objetos", contextClue: "Estrellas" },
  { word: "Microscopio", category: "Objetos", contextClue: "Laboratorio" },
  { word: "Calculadora", category: "Objetos", contextClue: "Cuentas" },
  { word: "Cuaderno", category: "Objetos", contextClue: "Hojas" },
  { word: "Lapicera", category: "Objetos", contextClue: "Tinta" },
  { word: "Goma de borrar", category: "Objetos", contextClue: "Lápiz" },
  { word: "Regla", category: "Objetos", contextClue: "Milímetros" },
  { word: "Engrampadora", category: "Objetos", contextClue: "Papel" },
  { word: "Cinta adhesiva", category: "Objetos", contextClue: "Pegar" },
  { word: "Tijera de podar", category: "Objetos", contextClue: "Jardín" },
  { word: "Manguera", category: "Objetos", contextClue: "Riego" },
  { word: "Pala", category: "Objetos", contextClue: "Tierra" },
  { word: "Rastrillo", category: "Objetos", contextClue: "Hojas secas" },
  { word: "Carretilla", category: "Objetos", contextClue: "Rueda" },
  { word: "Escalera", category: "Objetos", contextClue: "Peldaños" },
  { word: "Taladro", category: "Objetos", contextClue: "Mecha" },
  { word: "Serrucho", category: "Objetos", contextClue: "Dientes" },
  { word: "Nivel", category: "Objetos", contextClue: "Burbuja" },
  { word: "Cinta métrica", category: "Objetos", contextClue: "Medición" },
  { word: "Alicate", category: "Objetos", contextClue: "Cables" },
  { word: "Soldador", category: "Objetos", contextClue: "Estaño" },
  { word: "Casco", category: "Objetos", contextClue: "Protección" },
  { word: "Guantes", category: "Objetos", contextClue: "Manos" },
  { word: "Botiquín", category: "Objetos", contextClue: "Emergencia" },
  { word: "Termómetro", category: "Objetos", contextClue: "Fiebre" },
  { word: "Estetoscopio", category: "Objetos", contextClue: "Latidos" },
  { word: "Jeringa", category: "Objetos", contextClue: "Aguja" },
  { word: "Bicicleta", category: "Objetos", contextClue: "Cadena" },
  { word: "Patineta", category: "Objetos", contextClue: "Asfalto" },
  { word: "Pelota de fútbol", category: "Objetos", contextClue: "Gajos" },
  { word: "Raqueta de tenis", category: "Objetos", contextClue: "Encordado" },

  // Nuevos: Tecnología y Electrónica
  { word: "Smartphone", category: "Objetos", contextClue: "Pantalla táctil" },
  { word: "Notebook", category: "Objetos", contextClue: "Portátil" },
  { word: "Tablet", category: "Objetos", contextClue: "Tableta digital" },
  { word: "Teclado de computadora", category: "Objetos", contextClue: "Teclas y tipeo" },
  { word: "Mouse", category: "Objetos", contextClue: "Cursor" },
  { word: "Pendrive", category: "Objetos", contextClue: "Memoria USB" },
  { word: "Cargador de celular", category: "Objetos", contextClue: "Batería" },
  { word: "Cable USB", category: "Objetos", contextClue: "Conector" },
  { word: "Powerbank", category: "Objetos", contextClue: "Carga portátil" },
  { word: "Joystick", category: "Objetos", contextClue: "Consola de juegos" },
  { word: "Parlante Bluetooth", category: "Objetos", contextClue: "Música inalámbrica" },
  { word: "Smartwatch", category: "Objetos", contextClue: "Reloj inteligente" },
  { word: "Router Wi-Fi", category: "Objetos", contextClue: "Internet" },
  { word: "Impresora", category: "Objetos", contextClue: "Cartuchos" },
  { word: "Escáner", category: "Objetos", contextClue: "Digitalización" },
  { word: "Proyector", category: "Objetos", contextClue: "Cine en casa" },
  { word: "Disco rígido externo", category: "Objetos", contextClue: "Almacenamiento" },
  { word: "Trípode", category: "Objetos", contextClue: "Estabilidad de cámara" },
  { word: "Webcam", category: "Objetos", contextClue: "Videollamadas" },
  { word: "Consola de videojuegos", category: "Objetos", contextClue: "Entretenimiento gamer" },

  // Nuevos: Cocina y Bazar
  { word: "Pava eléctrica", category: "Objetos", contextClue: "Agua caliente" },
  { word: "Mate de calabaza", category: "Objetos", contextClue: "Infusión argentina" },
  { word: "Bombilla", category: "Objetos", contextClue: "Mate y filtro" },
  { word: "Yerbera", category: "Objetos", contextClue: "Recipiente de yerba" },
  { word: "Azucarera", category: "Objetos", contextClue: "Dulzor" },
  { word: "Licuadora", category: "Objetos", contextClue: "Batidos y cuchillas" },
  { word: "Batidora de mano", category: "Objetos", contextClue: "Repostería" },
  { word: "Exprimidor de cítricos", category: "Objetos", contextClue: "Jugo de naranja" },
  { word: "Wafflera", category: "Objetos", contextClue: "Masa crujiente" },
  { word: "Sandwichera", category: "Objetos", contextClue: "Tostados" },
  { word: "Freidora de aire", category: "Objetos", contextClue: "Cocina sin aceite" },
  { word: "Vaporera", category: "Objetos", contextClue: "Cocina al vapor" },
  { word: "Pelapapas", category: "Objetos", contextClue: "Vegetales" },
  { word: "Pisa papa", category: "Objetos", contextClue: "Puré" },
  { word: "Espumadera", category: "Objetos", contextClue: "Frituras" },
  { word: "Cucharón", category: "Objetos", contextClue: "Servir guiso" },
  { word: "Batidor de alambre", category: "Objetos", contextClue: "Huevos batidos" },
  { word: "Palo de amasar", category: "Objetos", contextClue: "Masa casera" },
  { word: "Tabla de picar", category: "Objetos", contextClue: "Corte en madera" },
  { word: "Salero", category: "Objetos", contextClue: "Condimento" },
  { word: "Pimentero", category: "Objetos", contextClue: "Granos molidos" },
  { word: "Aceitera", category: "Objetos", contextClue: "Ensaladas" },
  { word: "Asadera", category: "Objetos", contextClue: "Horno" },
  { word: "Molde de torta", category: "Objetos", contextClue: "Bizcochuelo" },
  { word: "Cubetera", category: "Objetos", contextClue: "Cubitos de hielo" },
  { word: "Tupper", category: "Objetos", contextClue: "Guardar comida" },
  { word: "Frasco de vidrio", category: "Objetos", contextClue: "Conservas" },
  { word: "Jarra de agua", category: "Objetos", contextClue: "Mesa servida" },
  { word: "Servilletero", category: "Objetos", contextClue: "Papel de mesa" },
  { word: "Balanza de cocina", category: "Objetos", contextClue: "Gramos exactos" },
  { word: "Mandolina", category: "Objetos", contextClue: "Láminas finas" },
  { word: "Parrilla", category: "Objetos", contextClue: "Asado" },
  { word: "Brasero", category: "Objetos", contextClue: "Carbón caliente" },
  { word: "Atizador", category: "Objetos", contextClue: "Brasas de fuego" },

  // Nuevos: Hogar, Limpieza y Muebles
  { word: "Escoba", category: "Objetos", contextClue: "Barrer piso" },
  { word: "Secador de piso", category: "Objetos", contextClue: "Goma y trapo" },
  { word: "Trapo de piso", category: "Objetos", contextClue: "Limpieza húmeda" },
  { word: "Balde", category: "Objetos", contextClue: "Agua con lavandina" },
  { word: "Plumero", category: "Objetos", contextClue: "Polvo en altura" },
  { word: "Broches de ropa", category: "Objetos", contextClue: "Tender sábanas" },
  { word: "Tendedero", category: "Objetos", contextClue: "Ropa al sol" },
  { word: "Cesto de basura", category: "Objetos", contextClue: "Residuos" },
  { word: "Felpudo", category: "Objetos", contextClue: "Bienvenida en puerta" },
  { word: "Cortina", category: "Objetos", contextClue: "Ventana" },
  { word: "Alfombra", category: "Objetos", contextClue: "Piso suave" },
  { word: "Sillón", category: "Objetos", contextClue: "Living y descanso" },
  { word: "Mesa ratona", category: "Objetos", contextClue: "Centro de sala" },
  { word: "Perchero", category: "Objetos", contextClue: "Colgar camperas" },
  { word: "Zapatero", category: "Objetos", contextClue: "Calzado ordenado" },
  { word: "Placard", category: "Objetos", contextClue: "Ropa guardada" },
  { word: "Percha", category: "Objetos", contextClue: "Prendas colgadas" },
  { word: "Florero", category: "Objetos", contextClue: "Ramos de flores" },
  { word: "Portarretrato", category: "Objetos", contextClue: "Foto familiar" },
  { word: "Reloj cucú", category: "Objetos", contextClue: "Péndulo y pájaro" },
  { word: "Ventilador de techo", category: "Objetos", contextClue: "Aire fresco" },
  { word: "Estufa halógena", category: "Objetos", contextClue: "Calor de invierno" },
  { word: "Aire acondicionado", category: "Objetos", contextClue: "Climatización" },
  { word: "Alcancía", category: "Objetos", contextClue: "Ahorro de monedas" },
  { word: "Caja fuerte", category: "Objetos", contextClue: "Valores protegidos" },

  // Nuevos: Herramientas y Taller
  { word: "Llave inglesa", category: "Objetos", contextClue: "Tuercas ajustables" },
  { word: "Llave Allen", category: "Objetos", contextClue: "Muebles para armar" },
  { word: "Pinza pico de loro", category: "Objetos", contextClue: "Plomería" },
  { word: "Tenaza", category: "Objetos", contextClue: "Sacar clavos" },
  { word: "Morsa de banco", category: "Objetos", contextClue: "Sujeción en taller" },
  { word: "Amoladora", category: "Objetos", contextClue: "Disco de corte" },
  { word: "Lijadora eléctrica", category: "Objetos", contextClue: "Madera suave" },
  { word: "Pistola de calor", category: "Objetos", contextClue: "Remover pintura" },
  { word: "Pistola de silicona", category: "Objetos", contextClue: "Pegamento caliente" },
  { word: "Cutter", category: "Objetos", contextClue: "Hoja afilada retráctil" },
  { word: "Cinta aisladora", category: "Objetos", contextClue: "Electricidad" },
  { word: "Espátula", category: "Objetos", contextClue: "Enduido y yeso" },
  { word: "Llana dentada", category: "Objetos", contextClue: "Colocación de cerámicos" },
  { word: "Remachadora", category: "Objetos", contextClue: "Unión metálica" },
  { word: "Gato hidráulico", category: "Objetos", contextClue: "Levantar el auto" },
  { word: "Llave cruz", category: "Objetos", contextClue: "Cambio de rueda" },
  { word: "Compresor de aire", category: "Objetos", contextClue: "Presión de neumáticos" },
  { word: "Baliza reflectante", category: "Objetos", contextClue: "Emergencia vial" },
  { word: "Matafuegos", category: "Objetos", contextClue: "Extintor de llamas" },
  { word: "Caja de herramientas", category: "Objetos", contextClue: "Organizador de taller" },
  { word: "Cinta de teflón", category: "Objetos", contextClue: "Rosca de caños" },
  { word: "Bulón", category: "Objetos", contextClue: "Fijación pesada" },
  { word: "Tarugo", category: "Objetos", contextClue: "Pared y taladro" },

  // Nuevos: Cuidado Personal, Ropa y Accesorios
  { word: "Cortaúñas", category: "Objetos", contextClue: "Manicura" },
  { word: "Lima de uñas", category: "Objetos", contextClue: "Uñas prolijas" },
  { word: "Secador de pelo", category: "Objetos", contextClue: "Peluquería" },
  { word: "Planchita de pelo", category: "Objetos", contextClue: "Alisado" },
  { word: "Máquina de afeitar", category: "Objetos", contextClue: "Barbería" },
  { word: "Cepillo de pelo", category: "Objetos", contextClue: "Desenredar" },
  { word: "Brocha de maquillaje", category: "Objetos", contextClue: "Cosméticos" },
  { word: "Labial", category: "Objetos", contextClue: "Color en labios" },
  { word: "Esmalte de uñas", category: "Objetos", contextClue: "Pintura de manicura" },
  { word: "Hisopo", category: "Objetos", contextClue: "Algodón para oídos" },
  { word: "Hilo dental", category: "Objetos", contextClue: "Higiene bucal" },
  { word: "Enjuague bucal", category: "Objetos", contextClue: "Aliento fresco" },
  { word: "Esponja vegetal", category: "Objetos", contextClue: "Ducha y baño" },
  { word: "Gorra con visera", category: "Objetos", contextClue: "Protección solar" },
  { word: "Gorro de lana", category: "Objetos", contextClue: "Frío en la cabeza" },
  { word: "Bufanda", category: "Objetos", contextClue: "Abrigo en el cuello" },
  { word: "Cinturón de cuero", category: "Objetos", contextClue: "Ajuste de pantalón" },
  { word: "Corbata", category: "Objetos", contextClue: "Traje formal" },
  { word: "Moño elegante", category: "Objetos", contextClue: "Fiesta de gala" },
  { word: "Tiradores", category: "Objetos", contextClue: "Sostén de pantalón" },
  { word: "Gemelos de camisa", category: "Objetos", contextClue: "Puños formales" },
  { word: "Anillo de compromiso", category: "Objetos", contextClue: "Joyería" },
  { word: "Collar de perlas", category: "Objetos", contextClue: "Alhajas" },
  { word: "Aros colgantes", category: "Objetos", contextClue: "Orejas decoradas" },
  { word: "Pulsera de plata", category: "Objetos", contextClue: "Muñeca" },
  { word: "Prendedor", category: "Objetos", contextClue: "Broche en solapa" },
  { word: "Riñonera", category: "Objetos", contextClue: "Bolso en cintura" },
  { word: "Monedero", category: "Objetos", contextClue: "Monedas guardadas" },
  { word: "Llavero", category: "Objetos", contextClue: "Manojo de llaves" },

  // Nuevos: Papelería, Oficina y Dibujo
  { word: "Resaltador fluorescente", category: "Objetos", contextClue: "Texto marcado" },
  { word: "Corrector líquido", category: "Objetos", contextClue: "Tapar error" },
  { word: "Sacapuntas", category: "Objetos", contextClue: "Punta de lápiz" },
  { word: "Compás", category: "Objetos", contextClue: "Círculos perfectos" },
  { word: "Transportador", category: "Objetos", contextClue: "Grados geométricos" },
  { word: "Escuadra", category: "Objetos", contextClue: "Ángulo recto" },
  { word: "Pincel", category: "Objetos", contextClue: "Pintura y acuarela" },
  { word: "Acuarelas", category: "Objetos", contextClue: "Colores al agua" },
  { word: "Caballete de pintura", category: "Objetos", contextClue: "Lienzo de artista" },
  { word: "Lienzo", category: "Objetos", contextClue: "Cuadro al óleo" },
  { word: "Pizarra blanca", category: "Objetos", contextClue: "Marcador borrable" },
  { word: "Borrador de pizarra", category: "Objetos", contextClue: "Limpiar pizarrón" },
  { word: "Clips metálicos", category: "Objetos", contextClue: "Sujetar hojas" },
  { word: "Chinches", category: "Objetos", contextClue: "Tablero de corcho" },
  { word: "Perforadora de hojas", category: "Objetos", contextClue: "Carpetas de anillos" },
  { word: "Carpeta con folios", category: "Objetos", contextClue: "Documentos archivados" },
  { word: "Sellos de goma", category: "Objetos", contextClue: "Tinta y firma" },
  { word: "Sobre de carta", category: "Objetos", contextClue: "Correo postal" },
  { word: "Estampilla", category: "Objetos", contextClue: "Franqueo postal" },
  { word: "Portaminas", category: "Objetos", contextClue: "Grafito fino" },
  { word: "Cartuchera", category: "Objetos", contextClue: "Útiles escolares" },

  // Nuevos: Deportes, Juegos e Instrumentos Musicales
  { word: "Flauta dulce", category: "Objetos", contextClue: "Viento madera" },
  { word: "Trompeta", category: "Objetos", contextClue: "Viento metal y pistones" },
  { word: "Saxofón", category: "Objetos", contextClue: "Jazz y boquilla" },
  { word: "Violín", category: "Objetos", contextClue: "Arco y cuerdas" },
  { word: "Violonchelo", category: "Objetos", contextClue: "Instrumento de piso" },
  { word: "Bajo eléctrico", category: "Objetos", contextClue: "Cuatro cuerdas graves" },
  { word: "Acordeón", category: "Objetos", contextClue: "Fuelle y teclas" },
  { word: "Armónica", category: "Objetos", contextClue: "Soplido y blues" },
  { word: "Pandereta", category: "Objetos", contextClue: "Cascabeles rítmicos" },
  { word: "Triángulo musical", category: "Objetos", contextClue: "Percusión metálica" },
  { word: "Xilófono", category: "Objetos", contextClue: "Láminas y baquetas" },
  { word: "Metrónomo", category: "Objetos", contextClue: "Tiempo y pulso" },
  { word: "Atril de música", category: "Objetos", contextClue: "Partituras" },
  { word: "Pelota de básquet", category: "Objetos", contextClue: "Aro y rebote" },
  { word: "Pelota de vóley", category: "Objetos", contextClue: "Red y saque" },
  { word: "Pelota de rugby", category: "Objetos", contextClue: "Forma ovalada" },
  { word: "Pelota de tenis", category: "Objetos", contextClue: "Fieltro amarillo" },
  { word: "Palo de hockey", category: "Objetos", contextClue: "Bocha y césped" },
  { word: "Palo de golf", category: "Objetos", contextClue: "Hoyo y green" },
  { word: "Bate de béisbol", category: "Objetos", contextClue: "Madera y jonrón" },
  { word: "Guante de boxeo", category: "Objetos", contextClue: "Ring y combate" },
  { word: "Silbato deportivo", category: "Objetos", contextClue: "Árbitro" },
  { word: "Cronómetro", category: "Objetos", contextClue: "Segundos de carrera" },
  { word: "Mancuerna", category: "Objetos", contextClue: "Gimnasio y pesas" },
  { word: "Cuerda para saltar", category: "Objetos", contextClue: "Entrenamiento cardio" },
  { word: "Colchoneta de yoga", category: "Objetos", contextClue: "Posturas y elongación" },
  { word: "Antiparras de natación", category: "Objetos", contextClue: "Pileta bajo el agua" },
  { word: "Snorkel", category: "Objetos", contextClue: "Respiración acuática" },
  { word: "Patines de cuatro ruedas", category: "Objetos", contextClue: "Pista de patinaje" },
  { word: "Rollers", category: "Objetos", contextClue: "Ruedas en línea" },
  { word: "Monopatín", category: "Objetos", contextClue: "Manubrio y tabla" },
  { word: "Tabla de surf", category: "Objetos", contextClue: "Olas del mar" },
  { word: "Barrilete", category: "Objetos", contextClue: "Vuelo con viento" },
  { word: "Trompo", category: "Objetos", contextClue: "Giro con piola" },
  { word: "Yoyó", category: "Objetos", contextClue: "Subibaja con hilo" },
  { word: "Cubo Rubik", category: "Objetos", contextClue: "Puzzle de colores" },
  { word: "Cartas de póker", category: "Objetos", contextClue: "Baraja de naipes" },
  { word: "Dados de casino", category: "Objetos", contextClue: "Puntos del 1 al 6" },
  { word: "Fichas de ajedrez", category: "Objetos", contextClue: "Rey y peones" },
  { word: "Tablero de damas", category: "Objetos", contextClue: "Casillas blancas y negras" },
  { word: "Reloj de arena", category: "Objetos", contextClue: "Paso del tiempo" },

  // Nuevos: Camping, Viaje y Aire Libre
  { word: "Carpa de camping", category: "Objetos", contextClue: "Noche al aire libre" },
  { word: "Bolsa de dormir", category: "Objetos", contextClue: "Aislamiento térmico" },
  { word: "Cantimplora", category: "Objetos", contextClue: "Hidratación en montaña" },
  { word: "Navaja suiza", category: "Objetos", contextClue: "Multiherramienta de bolsillo" },
  { word: "Caña de pescar", category: "Objetos", contextClue: "Anzuelo y reel" },
  { word: "Anzuelo", category: "Objetos", contextClue: "Carnada para peces" },
  { word: "Salvavidas", category: "Objetos", contextClue: "Flotación en agua" },
  { word: "Reposera", category: "Objetos", contextClue: "Playa y sol" },
  { word: "Sombrilla de playa", category: "Objetos", contextClue: "Sombra en la arena" },
  { word: "Conservadora de telgopor", category: "Objetos", contextClue: "Bebidas frías" },
  { word: "Binoculares", category: "Objetos", contextClue: "Visión lejana" },
  { word: "Lupa de aumento", category: "Objetos", contextClue: "Detalles microscópicos" },
  { word: "Campana de bronce", category: "Objetos", contextClue: "Sonido de campanario" },
  { word: "Herradura", category: "Objetos", contextClue: "Pata de caballo" },
  { word: "Imán potente", category: "Objetos", contextClue: "Atracción magnética" }
];

// Deduplicate by normalized word
const seen = new Set<string>();
const cleanObjects = [];
for (const item of newObjectsList) {
  const norm = item.word.trim().toLowerCase();
  if (!seen.has(norm)) {
    seen.add(norm);
    cleanObjects.push(item);
  }
}

fs.writeFileSync(OBJECTS_FILE, JSON.stringify(cleanObjects, null, 2), "utf-8");
console.log(`✅ Saved ${cleanObjects.length} unique objects in ${OBJECTS_FILE}`);
